### ISSUE TITLE
keycode "space" not interpreted in minibuffer during filter search

### ISSUE THREAD

**Issue by atanasj** [publicimageltd/notmuch-alerts#1]
I am using `doomemacs` with `evil-mode` and when using `notmuch-alert`, keycode "space" is not interpreted literally, but is interpreted as the leader key (which is "space" by default in `doomemacs`). 

In the GIF below, I am using accessing a `notmuch-bookmark` buffer without using `notmuch-alert`, then I use the latter to access the former.

This seems looks like a very useful package, but at the moment I cannot use it due to this problem. If you could please provide some support on how to fix this issue, that would be greatly appreciated.

![2023-03-17 19 47 39](https://user-images.githubusercontent.com/27214625/225857817-9f36dac1-7f87-43f9-9828-63790dd9d143.gif)

**Comment by publicimageltd** [comment]
First of all, wow, I did not think anyone ever uses `notmuch-bookmark` or `notmuch-alert`!

I have no idea why doom or evil doesn't let you use space in the completion. Under the hood, `completing-read` does the main work. I set no keymap or anything.

But looking at the GIF, space seems to work in some cases. So maybe you could describe the problem again? For example, is it possible to use space to filter the usual bookmarks list?

**Comment by publicimageltd** [comment]
Oh no wait, I was wrong, `notmuch-alert-visit` *does* change something! I'll have a look into it, but still feel free to explain the problem yet another time, I'm still not sure I understood it correctly.

**Comment by publicimageltd** [comment]
OK, I have an idea. The command uses a small hack to handle the problem that `completing-read` does not offer any wy to quit it except canceling it. I wanted something more elegant, so I decided I should be able to just press the invoking key once more in order to quit it. The workflow is: I press <f3>, check if there are any new mails, and press it again to continue working. I think it it this mechanism which is in the way.

So please check this hypotheses by setting `notmuch-alert-visit-quit-when-pressed-twice` to `nil` before calling `notmuch-alert-visit`. It should behave normal then.

**Comment by atanasj** [comment]
Yes, `(setq notmuch-alert-visit-quit-when-pressed-twice nil)` resolved it. Thanks!
